language: d
sudo: false
dist: bionic

branches:
  only:
    - master

notifications:
  email: true

d:
  - dmd-2.089.0
  # - dmd-2.088.1
  # - dmd-2.087.1
  # - dmd-2.086.1
  # - dmd-2.085.1
  # - ldc-1.18.0
  # - ldc-1.17.0
  # - ldc-1.16.0
  # - ldc-1.15.0
  # - ldc-1.14.0
  # - dmd-beta

# script:
#   - dub test --compiler=${DC}

jobs:
  include:
    # - stage: betterC
    #   script:
    #     - ./betterc_ut.sh
    # - stage: codecov
    #   script:
    #     - dub test -b unittest-cov --compiler=${DC}
    #     - bash <(curl -s https://codecov.io/bash)
    - stage: docs
      script:
        - wget https://github.com/adamdruppe/adrdox/archive/master.zip
        - unzip master.zip
        - pushd adrdox-master && make && popd
        - export PATH=$PATH:$PWD/adrdox-master
        - doc2 --genSearchIndex --genSource -o generated-docs source
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: generated-docs
        on:
          branch: master

env:
  global:
    secure: MoYZ74GYCq3aeoNSklsZ9TK4BdGWJSem4oRSb9XLxJMX07dWhCKrTFGoi7xYbRZd4I+rZaHCW7SCOn3YFaskpt+uL5+pryN/g0gWnVwVs+1DfHAwOgqt+sp6TgV/xueYqmXNiie2y9XK2iN75/wPXrh3yitxfRqSymzcmEwsniPFGLg2wqu+RCS+PBY9NYQiO7ySYxS+AqOiwelzTMPBd+tQcMxF9lvjaJNX+xP92m7gemZ/CeStyC3T+ySxsVjFjlkHW/neZ3e7sontSqqCmt95lHo3ujsC8P94AW0t1FsCwgoeyo/QpPhpp180z7LqkRC5Ud2vsLQKT1BlY6SooPsVeK7foXHh6r7zHXS3yL1oqFUJeJGO/fApXmckQdyZlh+FIpy0sLczOc9ug4jmdtpiNsX8u0D+frMIhj5cAJxb1qoDIIvxQFh57jCqEr6XvjcsKNfnWQuPKYPBOn4/LFp1L7LcjWrg7PeSpUPiTXAXRUujh7lzuPrefWfDYs4Q0ThxBKuUlz5iJNqzbS3B6A6x3M09nBgvZ9AsfQA9mTdqOE/pij6nXQHJO0TfIU27BOmKIEz+sbPzDiktAYsX8ut4wCwB0dHTUIyQrnbzC7pxxhNc8iuUUGdgng0Jzr8+OoVkO3SrHgS+v9WgWI+TzAkmLk7CC8I7Z3UBi1wdVJo=
